name: Build Devuan Root Filesystems

on:
  workflow_dispatch:

jobs:
  build_rootfs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            qemu_binary: qemu-aarch64-static
          - arch: armhf
            qemu_binary: qemu-arm-static
          - arch: armel
            qemu_binary: qemu-arm-static

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mmdebstrap qemu-user-static tar wget e2fsprogs

      - name: Download Devuan keyring
        run: |
          mkdir -p keyring_tmp
          cd keyring_tmp
          wget -q http://deb.devuan.org/merged/pool/DEVUAN/main/d/devuan-keyring/devuan-keyring_2026.01.13_all.deb
          ar x devuan-keyring_2026.01.13_all.deb
          tar -xf data.tar.xz
          cd ..

      - name: Build rootfs
        env:
          ROOTFS_DIR: ${{ github.workspace }}/devuan_${{ matrix.arch }}
        run: |
          sudo rm -rf "$ROOTFS_DIR"
          sudo mmdebstrap \
            --mode=unshare \
            --architectures=${{ matrix.arch }} \
            --keyring=$(pwd)/keyring_tmp/etc/apt/trusted.gpg.d/devuan-keyring-2016-archive.asc \
            --variant=minbase \
            --include=locales,tzdata,chrony,dropbear,sudo \
            --setup-hook='
              echo "localhost" > "$1/etc/hostname";
              echo "proc /proc proc defaults 0 0" > "$1/etc/fstab";
              chroot "$1" sh -c "echo root:debian123 | chpasswd";
              chroot "$1" sh -c "useradd -m -s /bin/bash user; echo user:debian123 | chpasswd; usermod -aG sudo user; echo \"user ALL=(ALL) NOPASSWD:ALL\" > /etc/sudoers.d/user; chmod 0440 /etc/sudoers.d/user";
              sed -i "/^[[:space:]]*pool/s/^/#/" "$1/etc/chrony/chrony.conf";
              sed -i "/^[[:space:]]*server/s/^/#/" "$1/etc/chrony/chrony.conf";
              echo "server ntp.tencent.com iburst" >> "$1/etc/chrony/chrony.conf";
              rm -rf "$1/var/log/*" "$1/tmp/*" "$1/usr/share/doc/*" "$1/usr/share/man/*" "$1/usr/share/info/*" "$1/var/lib/apt/lists/*"
            ' \
            stable \
            "$ROOTFS_DIR" \
            http://deb.devuan.org/merged

      - name: Compress rootfs
        run: |
          cd ${{ github.workspace }}
          tar czf devuan-rootfs-${{ matrix.arch }}.tar.gz -C $ROOTFS_DIR .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: devuan-rootfs-${{ matrix.arch }}
          path: devuan-rootfs-${{ matrix.arch }}.tar.gz
